from .loss import NeTFLoss

SPEED_OF_LIGHT = 299792458.0
EPOCHS_DEFAULT = 20
LOSS_LITERALS = [e.name for e in NeTFLoss]
TIME_BINS_DEFAULT = 4096
DELTA_METERS_DEFAULT = 0.003
DEVICE_DEFAULT = "cpu"
SENSOR_WIDTH_DEFAULT = 64
SENSOR_HEIGHT_DEFAULT = 64
LASER_WIDTH_DEFAULT = 64
LASER_HEIGHT_DEFAULT = 64
VOLUME_SAMPLES_DEFAULT = 50